import { Document, Model, Schema, model, Types } from "mongoose";

// ─── Enums ────────────────────────────────────────────────────────────────────

/** How the fall event was detected */
export enum FallDetectionMethod {
  ACCELEROMETER   = "accelerometer",    // Device motion sensor
  MANUAL_REPORT   = "manual_report",    // Elder pressed the "I fell" button
  WEARABLE        = "wearable",         // Smart watch / wearable device
  AI_PATTERN      = "ai_pattern",       // AI detected inactivity anomaly
  CAREGIVER_REPORT = "caregiver_report", // Family member reported it
}

/** Outcome/severity of the fall event */
export enum FallSeverity {
  MINOR    = "minor",     // No injury, got up independently
  MODERATE = "moderate",  // Some pain/bruising, needed minor help
  SEVERE   = "severe",    // Injury requiring medical attention
  CRITICAL = "critical",  // Emergency — ambulance called
  UNKNOWN  = "unknown",   // Severity not yet assessed
}

/** Current lifecycle state of the fall event */
export enum FallEventStatus {
  DETECTED     = "detected",     // Just detected — alerting family
  ACKNOWLEDGED = "acknowledged", // A family member has seen the alert
  RESPONDING   = "responding",   // Help is on the way
  RESOLVED     = "resolved",     // Event closed — elder is safe
  FALSE_ALARM  = "false_alarm",  // Elder confirmed they did NOT fall
}

// ─── Sub-document Interfaces ──────────────────────────────────────────────────

/** GPS coordinates at the moment of fall detection */
export interface IFallLocation {
  type: "Point";
  coordinates: [number, number];   // [longitude, latitude]
  accuracy?: number;               // Metres
  address?: string;                // Reverse-geocoded human-readable address
  indoorLocation?: string;         // "Kitchen", "Bathroom" (if known)
}

/** Timeline entry — every status change or action taken */
export interface IFallTimeline {
  timestamp: Date;
  status:    FallEventStatus;
  actor?:    Types.ObjectId;   // User who triggered this timeline event
  note?:     string;           // "Ambulance called", "Elder called back", etc.
}

/** Responder entry — who responded and how */
export interface IFallResponder {
  userId:          Types.ObjectId;
  respondedAt:     Date;
  responseMethod:  "app" | "call" | "physically_present";
  note?:           string;
}

/** Injury assessment filled post-event */
export interface IInjuryAssessment {
  injuryType?: string;            // "bruise", "fracture", "head injury", etc.
  bodyPart?:   string;            // "left hip", "right wrist", etc.
  medicalAttentionReceived: boolean;
  hospitalVisit:   boolean;
  hospitalName?:   string;
  doctorNotes?:    string;
  followUpRequired: boolean;
  followUpDate?:   Date;
}

/** Wearable sensor data captured at time of fall */
export interface ISensorData {
  accelerometerX?: number;
  accelerometerY?: number;
  accelerometerZ?: number;
  impactForce?:    number;     // g-force
  preImpactSpeed?: number;     // m/s
  heartRateAtFall?: number;    // bpm
  deviceModel?:    string;
  batteryLevel?:   number;     // %
}

// ─── Main Document Interface ──────────────────────────────────────────────────

export interface IFallEvent extends Document {
  /** The elder who fell */
  userId: Types.ObjectId;

  /** Family group — for fan-out notifications */
  familyId: Types.ObjectId;

  // ── Detection ───────────────────────────────────────────
  detectionMethod: FallDetectionMethod;
  detectedAt: Date;
  sensorData?: ISensorData;

  // ── Location ────────────────────────────────────────────
  location?: IFallLocation;

  // ── Severity & Status ───────────────────────────────────
  severity: FallSeverity;
  status:   FallEventStatus;

  // ── Timeline ────────────────────────────────────────────
  timeline: IFallTimeline[];

  // ── Responders ──────────────────────────────────────────
  responders: IFallResponder[];

  // ── Response Metrics ────────────────────────────────────
  /** How long (seconds) from detection to first acknowledgement */
  responseTimeSeconds?: number;

  /** How long (seconds) from detection to resolution */
  resolutionTimeSeconds?: number;

  // ── Elder Self-Report ───────────────────────────────────
  /** Did the elder confirm the fall was real? */
  elderConfirmed?: boolean;
  elderConfirmedAt?: Date;
  elderNote?: string;

  // ── SOS Integration ─────────────────────────────────────
  /** SOS alert generated by this fall event */
  sosAlertId?: Types.ObjectId;

  /** Was emergency services (911/999) called? */
  emergencyServicesCalled: boolean;
  emergencyServicesCalledAt?: Date;

  // ── Post-event Assessment ───────────────────────────────
  injuryAssessment?: IInjuryAssessment;

  /** AI-generated safety suggestions post-event */
  aiSafetySuggestions?: string[];

  // ── Flags ───────────────────────────────────────────────
  isFalseAlarm: boolean;
  requiresFollowUp: boolean;
  isReviewed: boolean;    // Family admin reviewed and closed this record
  reviewedBy?: Types.ObjectId;
  reviewedAt?: Date;

  // Timestamps
  createdAt: Date;
  updatedAt: Date;

  // ── Instance Methods ──────────────────────────────────────
  addTimelineEntry(
    status: FallEventStatus,
    actor?: Types.ObjectId,
    note?: string
  ): Promise<IFallEvent>;
}

/** Static helpers on FallEvent */
export interface IFallEventModel extends Model<IFallEvent> {
  getRecentFalls(userId: Types.ObjectId, days?: number): Promise<IFallEvent[]>;
  getFamilyFallStats(familyId: Types.ObjectId): Promise<{
    total: number;
    thisMonth: number;
    avgResponseTime: number;
  }>;
}

// ─── Sub-document Schemas ─────────────────────────────────────────────────────

const FallLocationSchema = new Schema<IFallLocation>(
  {
    type:           { type: String, enum: ["Point"], default: "Point" },
    coordinates:    { type: [Number], required: true },
    accuracy:       { type: Number },
    address:        { type: String, maxlength: 300 },
    indoorLocation: { type: String, maxlength: 100 },
  },
  { _id: false }
);

const FallTimelineSchema = new Schema<IFallTimeline>(
  {
    timestamp: { type: Date, default: Date.now },
    status:    { type: String, enum: Object.values(FallEventStatus), required: true },
    actor:     { type: Schema.Types.ObjectId, ref: "User" },
    note:      { type: String, maxlength: 300 },
  },
  { _id: true }
);

const FallResponderSchema = new Schema<IFallResponder>(
  {
    userId:         { type: Schema.Types.ObjectId, ref: "User", required: true },
    respondedAt:    { type: Date, default: Date.now },
    responseMethod: { type: String, enum: ["app", "call", "physically_present"], required: true },
    note:           { type: String, maxlength: 200 },
  },
  { _id: true }
);

const InjuryAssessmentSchema = new Schema<IInjuryAssessment>(
  {
    injuryType:                { type: String, maxlength: 100 },
    bodyPart:                  { type: String, maxlength: 100 },
    medicalAttentionReceived:  { type: Boolean, default: false },
    hospitalVisit:             { type: Boolean, default: false },
    hospitalName:              { type: String, maxlength: 150 },
    doctorNotes:               { type: String, maxlength: 1000 },
    followUpRequired:          { type: Boolean, default: false },
    followUpDate:              { type: Date },
  },
  { _id: false }
);

const SensorDataSchema = new Schema<ISensorData>(
  {
    accelerometerX:  { type: Number },
    accelerometerY:  { type: Number },
    accelerometerZ:  { type: Number },
    impactForce:     { type: Number },
    preImpactSpeed:  { type: Number },
    heartRateAtFall: { type: Number },
    deviceModel:     { type: String, maxlength: 100 },
    batteryLevel:    { type: Number, min: 0, max: 100 },
  },
  { _id: false }
);

// ─── Main Schema ──────────────────────────────────────────────────────────────

const FallEventSchema = new Schema<IFallEvent, IFallEventModel>(
  {
    // ── References ────────────────────────────────────────
    userId:   { type: Schema.Types.ObjectId, ref: "User",   required: true, index: true },
    familyId: { type: Schema.Types.ObjectId, ref: "Family", required: true, index: true },

    // ── Detection ─────────────────────────────────────────
    detectionMethod: {
      type: String, enum: Object.values(FallDetectionMethod),
      required: [true, "Detection method is required"],
    },
    detectedAt:  { type: Date, required: true, default: Date.now, index: true },
    sensorData:  { type: SensorDataSchema },

    // ── Location ──────────────────────────────────────────
    location: { type: FallLocationSchema },

    // ── Severity & Status ─────────────────────────────────
    severity: {
      type: String, enum: Object.values(FallSeverity),
      default: FallSeverity.UNKNOWN, index: true,
    },
    status: {
      type: String, enum: Object.values(FallEventStatus),
      default: FallEventStatus.DETECTED, index: true,
    },

    // ── Timeline ──────────────────────────────────────────
    timeline:   { type: [FallTimelineSchema], default: [] },
    responders: { type: [FallResponderSchema], default: [] },

    // ── Response Metrics ──────────────────────────────────
    responseTimeSeconds:   { type: Number, min: 0 },
    resolutionTimeSeconds: { type: Number, min: 0 },

    // ── Elder Confirmation ────────────────────────────────
    elderConfirmed:   { type: Boolean },
    elderConfirmedAt: { type: Date },
    elderNote:        { type: String, maxlength: 500 },

    // ── SOS Integration ───────────────────────────────────
    sosAlertId:                  { type: Schema.Types.ObjectId, ref: "SOSAlert" },
    emergencyServicesCalled:     { type: Boolean, default: false },
    emergencyServicesCalledAt:   { type: Date },

    // ── Post-event ───────────────────────────────────────
    injuryAssessment:     { type: InjuryAssessmentSchema },
    aiSafetySuggestions:  { type: [String], default: [] },

    // ── Flags ─────────────────────────────────────────────
    isFalseAlarm:     { type: Boolean, default: false },
    requiresFollowUp: { type: Boolean, default: false },
    isReviewed:       { type: Boolean, default: false },
    reviewedBy:       { type: Schema.Types.ObjectId, ref: "User" },
    reviewedAt:       { type: Date },
  },
  {
    timestamps: true,
    toJSON:   { virtuals: true },
    toObject: { virtuals: true },
  }
);

// ─── Indexes ──────────────────────────────────────────────────────────────────
FallEventSchema.index({ userId: 1, detectedAt: -1 });
FallEventSchema.index({ familyId: 1, status: 1 });
FallEventSchema.index({ familyId: 1, detectedAt: -1 });
FallEventSchema.index({ location: "2dsphere" });

// ─── Instance Methods ─────────────────────────────────────────────────────────

FallEventSchema.methods.addTimelineEntry = async function (
  this: IFallEvent,
  status: FallEventStatus,
  actor?: Types.ObjectId,
  note?: string
): Promise<IFallEvent> {
  this.timeline.push({ timestamp: new Date(), status, actor, note } as IFallTimeline);
  this.status = status;

  if (status === FallEventStatus.ACKNOWLEDGED && !this.responseTimeSeconds) {
    this.responseTimeSeconds = Math.round(
      (Date.now() - this.detectedAt.getTime()) / 1000
    );
  }
  if (
    (status === FallEventStatus.RESOLVED || status === FallEventStatus.FALSE_ALARM) &&
    !this.resolutionTimeSeconds
  ) {
    this.resolutionTimeSeconds = Math.round(
      (Date.now() - this.detectedAt.getTime()) / 1000
    );
    if (status === FallEventStatus.FALSE_ALARM) this.isFalseAlarm = true;
  }

  return this.save();
};

// ─── Static Methods ───────────────────────────────────────────────────────────

FallEventSchema.statics.getRecentFalls = function (
  userId: Types.ObjectId,
  days: number = 30
): Promise<IFallEvent[]> {
  const since = new Date();
  since.setDate(since.getDate() - days);
  return this.find({ userId, detectedAt: { $gte: since }, isFalseAlarm: false })
    .sort({ detectedAt: -1 });
};

FallEventSchema.statics.getFamilyFallStats = async function (familyId: Types.ObjectId) {
  const startOfMonth = new Date();
  startOfMonth.setDate(1);
  startOfMonth.setHours(0, 0, 0, 0);

  const [stats] = await this.aggregate([
    { $match: { familyId, isFalseAlarm: false } },
    {
      $group: {
        _id: null,
        total:       { $sum: 1 },
        thisMonth:   { $sum: { $cond: [{ $gte: ["$detectedAt", startOfMonth] }, 1, 0] } },
        avgResponse: { $avg: "$responseTimeSeconds" },
      },
    },
  ]);

  return stats
    ? { total: stats.total, thisMonth: stats.thisMonth, avgResponseTime: Math.round(stats.avgResponse ?? 0) }
    : { total: 0, thisMonth: 0, avgResponseTime: 0 };
};

// ─── Export ───────────────────────────────────────────────────────────────────
const FallEvent = model<IFallEvent, IFallEventModel>("FallEvent", FallEventSchema);
export default FallEvent;
